# Generated by Django 3.0.3 on 2020-03-06 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('open_id', models.CharField(default='', max_length=100, null=True)),
                ('cus_tel_num', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('cus_name', models.CharField(default='', max_length=100, null=True)),
                ('cus_nickname', models.CharField(default='', max_length=20, null=True)),
                ('cus_wanting_cars', models.CharField(default='', max_length=20, null=True)),
                ('cus_wanting_reason', models.CharField(default='', max_length=20, null=True)),
                ('cus_coming_rules', models.CharField(default='', max_length=20, null=True)),
                ('cus_wanting_level', models.IntegerField(default=0, null=True)),
                ('cus_coming_counts', models.IntegerField(default=1, null=True)),
                ('cus_next_following_time', models.DateTimeField(null=True)),
                ('cus_coming_time', models.DateTimeField(null=True)),
                ('cus_following_time', models.DateTimeField(null=True)),
                ('cus_first_coming_time', models.DateTimeField(null=True)),
                ('cus_treat_counts', models.IntegerField(default=0, null=True)),
                ('cus_adress', models.CharField(default='', max_length=5, null=True)),
                ('cus_budget', models.IntegerField(default=0, null=True)),
                ('cus_sex', models.CharField(default='', max_length=8, null=True)),
                ('cus_avatarurl', models.CharField(default='', max_length=100, null=True)),
                ('cus_creating_time', models.DateTimeField(null=True)),
                ('cus_sign', models.CharField(default='0', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('open_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('user_name', models.CharField(max_length=20)),
                ('avatar_url', models.CharField(max_length=200)),
                ('tel_num', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cus_Follow_Record',
            fields=[
                ('open_id', models.CharField(default='', max_length=100, null=True)),
                ('cus_follow_time', models.DateTimeField(primary_key=True, serialize=False)),
                ('cus_next_following_time', models.DateTimeField(null=True)),
                ('cus_wanting_cars', models.CharField(default='', max_length=20, null=True)),
                ('cus_wangting_level', models.IntegerField(default=0, null=True)),
                ('cus_budget', models.IntegerField(default=0, null=True)),
                ('mark', models.TextField(default='', null=True)),
                ('cus_tel_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Customer')),
            ],
        ),
    ]
