# Generated by Django 3.0.3 on 2020-02-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('open_id', models.CharField(default='', max_length=100, null=True)),
                ('cus_tel_num', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('cus_name', models.CharField(default='', max_length=100, null=True)),
                ('cus_nickname', models.CharField(default='', max_length=20, null=True)),
                ('cus_wanting_cars', models.CharField(default='', max_length=20, null=True)),
                ('cus_wanting_reason', models.CharField(default='', max_length=15, null=True)),
                ('cus_wanting_level', models.CharField(default='', max_length=3, null=True)),
                ('cus_following_counts', models.IntegerField(default='', null=True)),
                ('cus_coming_counts', models.IntegerField(default='', null=True)),
                ('cus_next_following_time', models.DateTimeField(default='', null=True)),
                ('cus_coming_time', models.DateTimeField(default='', null=True)),
                ('cus_following_days', models.IntegerField(default='', null=True)),
                ('cus_treat_coounts', models.IntegerField(default='', null=True)),
                ('cus_adress', models.CharField(default='', max_length=5, null=True)),
                ('cus_budget', models.CharField(default='', max_length=10, null=True)),
                ('cus_sex', models.CharField(default='', max_length=8, null=True)),
                ('cus_avatarurl', models.CharField(default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('open_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('user_name', models.CharField(max_length=20)),
                ('avatar_url', models.CharField(max_length=200)),
                ('tel_num', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
