# Generated by Django 3.0.3 on 2020-03-07 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cus_Sign_Record',
            fields=[
                ('open_id', models.CharField(default='', max_length=100, null=True)),
                ('cus_sign_time', models.DateTimeField(primary_key=True, serialize=False)),
                ('cus_buying_cars', models.CharField(default='', max_length=20, null=True)),
                ('cus_cost', models.IntegerField(default=0, null=True)),
                ('cus_tel_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Customer')),
            ],
        ),
    ]
